version: '3.6'
services:
  gitlab:
    image: gitlab/gitlab-ce:16.9.8-ce.0
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_ROOT_EMAIL: 'root@local'
      GITLAB_ROOT_PASSWORD: '123qweASDF#'
      GITLAB_OMNIBUS_CONFIG: |
        # Add any other gitlab.rb configuration here, each on its own line
        external_url 'http://localhost'
    ports:
      - '8081:80'
      # - '443:443'
      - '22:22'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    shm_size: '256m'
    env_file:
      - .env